/* tslint:disable */
/* eslint-disable */
/**
 * Bratislava Enforcement scan app backend
 * Enforcement backend for mobile app for lustrating and creating penalties for bad parking and traffic violations
 *
 * The version of the OpenAPI document: 1.0
 * Contact: inovacie@bratislava.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api'
export * from './configuration'
